"use client";

import { useState } from "react";

function Box({ title, children }: { title: string; children: React.ReactNode }) {
  return <section style={{ border: "1px solid #e5e7eb", borderRadius: 16, padding: 20, background: "white", marginBottom: 20 }}><h2>{title}</h2>{children}</section>;
}
function Field(props: any) { return <input {...props} style={{ width: "100%", padding: 12, borderRadius: 10, border: "1px solid #cbd5e1", marginBottom: 10, boxSizing: "border-box" }} />; }
function TextArea(props: any) { return <textarea {...props} style={{ width: "100%", minHeight: 120, padding: 12, borderRadius: 10, border: "1px solid #cbd5e1", marginBottom: 10, boxSizing: "border-box" }} />; }
function Button({ children, onClick }: { children: React.ReactNode; onClick: () => void }) { return <button onClick={onClick} style={{ padding: "12px 16px", borderRadius: 10, border: "none", background: "#111827", color: "white", cursor: "pointer", fontWeight: 700, marginRight: 8, marginBottom: 8 }}>{children}</button>; }

export default function AdminPage() {
  const [secret, setSecret] = useState("");
  const [githubSecret, setGithubSecret] = useState("");
  const [mcpSecret, setMcpSecret] = useState("");
  const [input, setInput] = useState("AI와 인간의 미래");
  const [branch, setBranch] = useState("feature/onemind-test");
  const [filePath, setFilePath] = useState("docs/onemind-test.md");
  const [fileContent, setFileContent] = useState("# OneMind Test\n\nGenerated by DEVO-AI-OS v2.0.");
  const [result, setResult] = useState<any>(null);

  async function callApi(path: string, body?: any, mode: "none" | "devo" | "github" | "mcp" = "none") {
    try {
      const headers: any = { "Content-Type": "application/json" };
      if (mode === "devo") headers["x-devo-secret"] = secret;
      if (mode === "github") headers["x-devo-secret"] = githubSecret;
      if (mode === "mcp") headers["x-devo-secret"] = mcpSecret;
      const res = await fetch(path, { method: body ? "POST" : "GET", headers, body: body ? JSON.stringify(body) : undefined });
      setResult(await res.json());
    } catch (error: any) {
      setResult({ ok: false, error: error.message });
    }
  }

  return (
    <main style={{ minHeight: "100vh", background: "linear-gradient(180deg,#f8fafc,#eef2ff)", padding: 32, fontFamily: "Arial, sans-serif" }}>
      <div style={{ maxWidth: 1100, margin: "0 auto" }}>
        <h1>DEVO-AI-OS v2.0 Admin</h1>
        <p>OneMind · GitHub · Canva · MCP · Memory · Vercel</p>

        <Box title="Secrets">
          <Field type="password" value={secret} onChange={(e:any)=>setSecret(e.target.value)} placeholder="DEVO_API_SECRET" />
          <Field type="password" value={githubSecret} onChange={(e:any)=>setGithubSecret(e.target.value)} placeholder="GITHUB_API_SECRET" />
          <Field type="password" value={mcpSecret} onChange={(e:any)=>setMcpSecret(e.target.value)} placeholder="MCP_API_SECRET" />
        </Box>

        <Box title="OneMind Creative Workflow">
          <Field value={input} onChange={(e:any)=>setInput(e.target.value)} />
          <Button onClick={() => callApi("/api/onemind", { input })}>Run OneMind Engine</Button>
          <Button onClick={() => callApi("/api/openai", { input })}>Run Router</Button>
          <Button onClick={() => callApi("/api/canva", { input })}>Generate Canva Brief</Button>
        </Box>

        <Box title="System">
          <Button onClick={() => callApi("/api/health")}>Health</Button>
          <Button onClick={() => callApi("/api/engines")}>Engines</Button>
          <Button onClick={() => callApi("/api/mcp", undefined, "mcp")}>MCP Tools</Button>
        </Box>

        <Box title="GitHub Control">
          <Field value={branch} onChange={(e:any)=>setBranch(e.target.value)} />
          <Field value={filePath} onChange={(e:any)=>setFilePath(e.target.value)} />
          <TextArea value={fileContent} onChange={(e:any)=>setFileContent(e.target.value)} />
          <Button onClick={() => callApi("/api/github", { action: "repo_info" }, "github")}>Repo Info</Button>
          <Button onClick={() => callApi("/api/github", { action: "refactor_commit_pr", newBranch: branch, files: [{ path: filePath, content: fileContent, message: `Update ${filePath}` }], prTitle: `OneMind PR: ${filePath}`, prBody: "Generated from DEVO-AI-OS v2.0 Admin." }, "github")}>Branch → Commit → PR</Button>
        </Box>

        <Box title="Vercel / Memory">
          <Button onClick={() => callApi("/api/vercel", { action: "trigger_deploy" }, "devo")}>Trigger Deploy</Button>
          <Button onClick={() => callApi("/api/memory", { action: "remember", key: "onemind", value: input }, "devo")}>Remember Topic</Button>
          <Button onClick={() => callApi("/api/memory", { action: "recall" }, "devo")}>Recall</Button>
        </Box>

        <Box title="Result">
          <pre style={{ whiteSpace: "pre-wrap", wordBreak: "break-word", background: "#0f172a", color: "#e2e8f0", padding: 16, borderRadius: 12 }}>{result ? JSON.stringify(result, null, 2) : "결과가 여기에 표시됩니다."}</pre>
        </Box>
      </div>
    </main>
  );
}
