"use client";

import { useState } from "react";

function Box({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section style={{
      border: "1px solid #e5e7eb",
      borderRadius: 16,
      padding: 20,
      background: "white",
      boxShadow: "0 8px 24px rgba(0,0,0,0.04)",
      marginBottom: 20
    }}>
      <h2 style={{ marginTop: 0 }}>{title}</h2>
      {children}
    </section>
  );
}

function Field(props: any) {
  return (
    <input
      {...props}
      style={{
        width: "100%",
        padding: 12,
        borderRadius: 10,
        border: "1px solid #cbd5e1",
        marginBottom: 10,
        fontSize: 14,
        boxSizing: "border-box"
      }}
    />
  );
}

function TextArea(props: any) {
  return (
    <textarea
      {...props}
      style={{
        width: "100%",
        minHeight: 130,
        padding: 12,
        borderRadius: 10,
        border: "1px solid #cbd5e1",
        marginBottom: 10,
        fontSize: 14,
        fontFamily: "monospace",
        boxSizing: "border-box"
      }}
    />
  );
}

function Button({ children, onClick }: { children: React.ReactNode; onClick: () => void }) {
  return (
    <button
      onClick={onClick}
      style={{
        padding: "12px 16px",
        borderRadius: 10,
        border: "none",
        background: "#111827",
        color: "white",
        cursor: "pointer",
        fontWeight: 700,
        marginRight: 8,
        marginBottom: 8
      }}
    >
      {children}
    </button>
  );
}

export default function AdminPage() {
  const [secret, setSecret] = useState("");
  const [githubSecret, setGithubSecret] = useState("");
  const [mcpSecret, setMcpSecret] = useState("");
  const [input, setInput] = useState("Canva Agent Engine를 만들어줘");
  const [canvaInput, setCanvaInput] = useState("AI 교육 발표자료");
  const [filePath, setFilePath] = useState("docs/admin-test.md");
  const [fileContent, setFileContent] = useState("# Admin Test\\n\\nGenerated by DEVO-AI-OS Admin.");
  const [branch, setBranch] = useState("feature/admin-test");
  const [result, setResult] = useState<any>(null);

  async function callApi(path: string, body?: any, mode: "devo" | "github" | "mcp" | "none" = "none") {
    try {
      const headers: any = { "Content-Type": "application/json" };

      if (mode === "github") headers["x-devo-secret"] = githubSecret;
      if (mode === "mcp") headers["x-devo-secret"] = mcpSecret;
      if (mode === "devo") headers["x-devo-secret"] = secret;

      const res = await fetch(path, {
        method: body ? "POST" : "GET",
        headers,
        body: body ? JSON.stringify(body) : undefined
      });

      const data = await res.json();
      setResult(data);
    } catch (error: any) {
      setResult({ ok: false, error: error.message });
    }
  }

  return (
    <main style={{
      minHeight: "100vh",
      background: "linear-gradient(180deg,#f8fafc,#eef2ff)",
      padding: 32,
      fontFamily: "Arial, sans-serif"
    }}>
      <div style={{ maxWidth: 1100, margin: "0 auto" }}>
        <h1 style={{ fontSize: 42, marginBottom: 8 }}>DEVO-AI-OS Admin</h1>
        <p style={{ color: "#475569", fontSize: 18 }}>
          GitHub · Canva · OpenAI Router · Memory · MCP · Vercel Deploy Control Panel
        </p>

        <Box title="Secrets">
          <label>DEVO_API_SECRET</label>
          <Field type="password" value={secret} onChange={(e: any) => setSecret(e.target.value)} placeholder="DEVO_API_SECRET" />
          <label>GITHUB_API_SECRET</label>
          <Field type="password" value={githubSecret} onChange={(e: any) => setGithubSecret(e.target.value)} placeholder="GITHUB_API_SECRET" />
          <label>MCP_API_SECRET</label>
          <Field type="password" value={mcpSecret} onChange={(e: any) => setMcpSecret(e.target.value)} placeholder="MCP_API_SECRET" />
        </Box>

        <Box title="System Check">
          <Button onClick={() => callApi("/api/health")}>Health Check</Button>
          <Button onClick={() => callApi("/api/engines")}>List Engines</Button>
          <Button onClick={() => callApi("/api/mcp", undefined, "mcp")}>MCP Tools</Button>
        </Box>

        <Box title="OpenAI / Workflow Router">
          <Field value={input} onChange={(e: any) => setInput(e.target.value)} />
          <Button onClick={() => callApi("/api/openai", { input })}>Run Router</Button>
          <Button onClick={() => callApi("/api/openai", { input, use_openai: true })}>Run OpenAI</Button>
        </Box>

        <Box title="Canva Design Agent">
          <Field value={canvaInput} onChange={(e: any) => setCanvaInput(e.target.value)} />
          <Button onClick={() => callApi("/api/canva", { input: canvaInput })}>Generate Canva Brief</Button>
        </Box>

        <Box title="GitHub Control Panel">
          <label>Branch</label>
          <Field value={branch} onChange={(e: any) => setBranch(e.target.value)} />
          <label>File Path</label>
          <Field value={filePath} onChange={(e: any) => setFilePath(e.target.value)} />
          <label>File Content</label>
          <TextArea value={fileContent} onChange={(e: any) => setFileContent(e.target.value)} />

          <Button onClick={() => callApi("/api/github", { action: "repo_info" }, "github")}>Repo Info</Button>
          <Button onClick={() => callApi("/api/github", { action: "create_branch", newBranch: branch, baseBranch: "main" }, "github")}>Create Branch</Button>
          <Button onClick={() => callApi("/api/github", { action: "write_file", branch, path: filePath, content: fileContent, message: `Update ${filePath}` }, "github")}>Write File / Commit</Button>
          <Button onClick={() => callApi("/api/github", { action: "create_pr", head: branch, base: "main", title: `Admin update: ${filePath}`, body: "Generated from DEVO-AI-OS Admin Panel." }, "github")}>Create PR</Button>
          <Button onClick={() => callApi("/api/github", {
            action: "refactor_commit_pr",
            taskName: "admin-test",
            newBranch: branch,
            files: [{ path: filePath, content: fileContent, message: `Update ${filePath}` }],
            prTitle: `Admin PR: ${filePath}`,
            prBody: "Branch, commit and PR generated from DEVO-AI-OS Admin Panel.",
            triggerDeploy: false
          }, "github")}>Branch → Commit → PR</Button>
        </Box>

        <Box title="Vercel Deploy">
          <Button onClick={() => callApi("/api/vercel", { action: "trigger_deploy" }, "devo")}>Trigger Deploy Hook</Button>
        </Box>

        <Box title="Agent Memory">
          <Button onClick={() => callApi("/api/memory", { action: "remember", key: "admin", value: "Admin panel tested" }, "devo")}>Remember Test</Button>
          <Button onClick={() => callApi("/api/memory", { action: "recall" }, "devo")}>Recall Memory</Button>
          <Button onClick={() => callApi("/api/memory", { action: "clear" }, "devo")}>Clear Memory</Button>
        </Box>

        <Box title="Result">
          <pre style={{
            whiteSpace: "pre-wrap",
            wordBreak: "break-word",
            background: "#0f172a",
            color: "#e2e8f0",
            padding: 16,
            borderRadius: 12,
            minHeight: 160
          }}>
            {result ? JSON.stringify(result, null, 2) : "결과가 여기에 표시됩니다."}
          </pre>
        </Box>
      </div>
    </main>
  );
}
